update pre-push hook to make sure on correct branch and stuff

diff --git a/git_hooks/pre-push b/git_hooks/pre-push
--- a/git_hooks/pre-push
+++ b/git_hooks/pre-push
@@ -3,6 +3,12 @@
 local_master_hash="$(git rev-parse master)"
 origin_master_hash="$(git rev-parse origin/master)"
 
+if ! git diff --exit-code --quiet HEAD -- $(git rev-parse --show-toplevel)/_mirror_code/script.gs; then
+  echo "ERROR: Uncommitted changes in _mirror_code/script.gs"
+  echo "please commit these changes before pushing."
+  exit 3;
+fi
+
 if [ "$local_master_hash" = "$origin_master_hash" ]; then
   echo "Local and origin repos match master branch."
   echo "skipping pre-push check..."
@@ -12,7 +18,7 @@ echo "Local and origin repos have different master branches."
 echo "proceeding with pre-push hook."
 
 echo "comparing local _mirror_code/script.gs to deployed script.gs"
-if [ "git branch --show-current" != "master" ]; then
+if [ "$(git branch --show-current)" != "master" ]; then
   echo "ERROR: current branch needs to be master for script comparison!"
   echo "cancelling push."
   exit 2;
