updated pre-push hook to only check master branch

diff --git a/git_hooks/pre-push b/git_hooks/pre-push
--- a/git_hooks/pre-push
+++ b/git_hooks/pre-push
@@ -1,5 +1,23 @@
 #!/bin/sh
 
+local_master_hash="$(git rev-parse master)"
+origin_master_hash="$(git rev-parse origin/master)"
+
+if [ "$local_master_hash" = "$origin_master_hash" ]; then
+  echo "Local and origin repos match master branch."
+  echo "skipping pre-push check..."
+  exit 0;
+fi
+echo "Local and origin repos have different master branches."
+echo "proceeding with pre-push hook."
+
+echo "comparing local _mirror_code/script.gs to deployed script.gs"
+if [ "git branch --show-current" != "master" ]; then
+  echo "ERROR: current branch needs to be master for script comparison!"
+  echo "cancelling push."
+  exit 2;
+fi
+
 # Silently check if local script.gs matches deployed script.gs
 if $(git rev-parse --show-toplevel)/_mirror_code/test_gs.sh -s; then
 	# zero exit status. No differences.
